### ISSUE TITLE
sudo docker-compose -f docker-compose-with-cfadmin.yaml up 运行失败

### ISSUE THREAD

**Issue by exyoyou** [CandyMi/cfadmin#15]
sudo docker-compose -f docker-compose-with-cfadmin.yaml up
Removing docker_WebDB_1
Recreating 83fbed6029b8_docker_WebDB_1 ... 

ERROR: for 83fbed6029b8_docker_WebDB_1  a bytes-like object is required, not 'str'

ERROR: for WebDB  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/cdc1bfccb594fce8c8fae0d578a88a54fb3aba2b477bc84e56f8fcb2c37e81a8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint docker_WebDB_1 (6c74d89f66aabbe75f58589e459f17ced5c13ea5b049b631340d4c12cf021a36): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 561, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 486, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 481, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 602, in recreate_container
    self.start_container(new_container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
 第一次发现这个 但是运行不了 不知道那里的问题 希望大神提点一下  谢谢啦

**Comment by CandyMi** [comment]
@yg-jiugui 

从您这边的反馈错误信息来看, 更像是`docker-compose`出错了.  我这边可以给出的以下建议:

  * 检查安装版本之间是否有冲突;

  * 检查安装过程是否正常;

**Comment by CandyMi** [comment]
@yg-jiugui 

  如果检查还是有问题的话! 可以先停止所有正在运行的容器, 然后再次运行之前的启动命令尝试.

**Comment by exyoyou** [comment]
> @ yg-jiugui
> 
> 从您这边的反馈错误信息来看，更像是`docker-compose`出错了。我这边可以告知的以下建议：
> 
> * 检查安装版本之间是否存在冲突；
> * 检查安装过程是否正常；

谢谢   我ubuntu 下 重新安装docker-ce 在官网有详细的安装教程   之前安装的是docker所以运行它一直报错误。   




我运行这个 sudo docker-compose -f docker-compose-with-cfadmin.yaml up 
![ae4e66d769c46d4c95409cf411a8800b](https://user-images.githubusercontent.com/64944848/86220727-949d4c00-bbb6-11ea-82b6-3c91c6a45d23.png)我这mysql用的不是root用户 但是不知道这里应该改为什么呢 现在在这里一直错误 我想应该是这里有问题吗？main.lua方法中配置也是 username不是root


WebApp_1  | [2020-07-01 08:13:00,128] [@lualib/DB/init.lua:51] [WARN] : "The connection failed. The reasons are: [MySQL Authentication protocol not supported], Try to reconnect after 3 seconds" 
docker_WebDB_1 exited with code 127
WebApp_1  | [2020-07-01 08:13:00,332] [@lualib/DB/init.lua:51] [WARN] : "The connection failed. The reasons are: [MySQL Authentication protocol not supported], Try to reconnect after 3 seconds" 
WebApp_1  | [2020-07-01 08:13:00,543] [@lualib/DB/init.lua:51] [WARN] : "The connection failed. The reasons are: [MySQL Authentication protocol not supported], Try to reconnect after 3 seconds" 
WebApp_1  | [2020-07-01 08:13:00,748] [@lualib/DB/init.lua:51] [WARN] : "The connection failed. The reasons are: [MySQL Authentication protocol not supported], Try to reconnect after 3 seconds"

**Comment by CandyMi** [comment]
@yg-jiugui 

根据错误提示可以判断应该是连接协议有问题! 

但是并不能排除您配置的账户、密码是否正确, 这个需要您自行确认.  :)

根据您的回应, 需要说明的是:

  * 你在`docker-compose`文件使用的MySQL镜像在[这里](https://hub.docker.com/_/mysql), 可以从此处查看镜像使用帮助.

  * 目前`master`分支的协议已经支持8.x连接, 您可以将`command: default-authentication-plugin=mysql_native_password` 注释后再尝试是否可以正常使用.

  * `docker`文件夹内的相关`docker-compose`文件都是可配置性较低的东西, 如果您本地编译或使用安装包安装会更加简单;

最后我给您一些建议:

  * 根据您要灵活定制的需求最好是自建镜像最优, 其他使用者都有自己构建开发、生产环境镜像的习惯;

  * 需要知道的是, `docker`内的示例都是以演示为主. 如果构建镜像对您的环境有一定难度的话, 也优先建议您编译安装后开发调试. 

  * 如果您对本机安装、配置、编译等等还是有其他的疑问. 可以加入项目首页的交流群, 这样能得到更多人、更加时效的回答.
